[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "chgnet"
version = "0.0.1"
description = "Pretrained Neural Network Potential for Charge-informed Molecular Dynamics"
authors = [
    {name = "Bowen Deng", email = "bowendeng@berkeley.edu"}
]
readme = "README.md"
license = {text = "MIT"}
dependencies = [
        "numpy~=1.21.6",
        "torch~=1.11.0",
        "pymatgen~=2022.4.19",
        "ase==3.22.0",
    ]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.urls]
Source = "https://github.com/CederGroupHub/chgnet"

[tool.setuptools.packages.find]
where = ["chgnet"]

[tool.setuptools.package-data]
chgnet = ["chgnet/pretrained/*"]

[tool.ruff]
target-version = "py38"
select = [
    "B",   # flake8-bugbear
    "D",   # pydocstyle
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "PLE", # pylint error
    "PLW", # pylint warning
    "PYI", # flakes8-pyi
    "Q",   # flake8-quotes
    "SIM", # flake8-simplify
    "TID", # tidy imports
    "UP",  # pyupgrade
    "W",   # pycodestyle
    "YTT", # flake8-2020
]
ignore = [
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
    "D205",   # 1 blank line required between summary line and description
    "SIM105", # Use contextlib.suppress(FileNotFoundError) instead of try-except-pass
    "SIM115", # Use context handler for opening files
]
pydocstyle.convention = "google"
isort.required-imports = ["from __future__ import annotations"]

[tool.ruff.per-file-ignores]
"tests/*" = ["D103"]
"examples/*" = ["E402"] # E402 Module level import not at top of file
